### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mdestafadilah** [wuxiaobai24/aa-gatsby-blog#31]
..\components\cards\tags-card.js
7:24  error  Field "field" is not defined by type MdxFilterInput  graphql/template-strings

**Comment by wuxiaobai24** [comment]
hello, this repo was only used by me at first, so i don't write a README file.
I use a **private** repo to save the markdown file of my blog post, and use the [gatsby-source-git](https://www.gatsbyjs.com/plugins/gatsby-source-git/) plugin to get it, so you need to modify repo url in the [gatsby-config.js file](https://github.com/wuxiaobai24/aa-gatsby-blog/blob/e93c1fb833b42561ab4e5a8049c094ab7e789300/gatsby-config.js#L23), or you can use the [gatsby-source-filesystem](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/) plugin replaces the gatsby-source-git plugin.
At the same time, my markdown file contains a yaml front matter, such as:
```
---
title: Use Travis CI
date: 2019-08-20T00:30:27.000Z
tags:
  - CI/CD
  - Hexo
categories:
  - Blog
---

some content
```

**Comment by mdestafadilah** [comment]
Hi,
Thanks for your reply, Yes, i like your design, simple and elegant, so i'm testing it in my local dev. I will test it with your direction. and btw, where your put your folder for markdown file? and what typed file name for markdown file?

**Comment by wuxiaobai24** [comment]
1. i save my markdown file in `./content`, you can find some configuration in [here](https://github.com/wuxiaobai24/aa-gatsby-blog/blob/e93c1fb833b42561ab4e5a8049c094ab7e789300/gatsby-config.js#L25). 
2. `.md` and `.mdx` is ok.

**Comment by mdestafadilah** [comment]
Yes, it's working now. I'm replace it with here 
```
  {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "posts",
        path: `${__dirname}/content/`
      }
    },
```
but get some notice error or warning, i think.
```
success Re-building development bundle - 0.195s
warning Error persisting state: function mathPlugin (opts) {
  if (opts == null) opts = {}
  blockPlugin.call(this, opts)
  inlinePlugin.call(this, opts)
} could not be cloned.
```
do you know, whats problem it's ?

**Comment by wuxiaobai24** [comment]
I also get this warning. There is a conflict between gatsby-plugin-mdx and gatsby-remark-katex. Maybe you can fix this warning by following [this blog](https://nickymeuleman.netlify.app/blog/math-gatsby-mdx)(BTW,I have not tested)
